name: Arkit
on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Init
        uses: actions/setup-node@v2
        with:
          node-version: 17
          cache: yarn
      - name: Create the Arkit image
        run: |
          yarn
          yarn arkit:components
      - name: Upload the image
        uses: devicons/public-upload-to-imgur@v2.2.1
        id: imgur_step
        with:
          path: ./components.png
          client_id: ${{secrets.IMGUR_CLIENT_ID}}
          uses: github-actions-up-and-running/pr-comment@v1.0.1
          env:
            IMG_URL: ${{ fromJSON(steps.imgur_step.outputs.imgur_urls)[0] }}
            MESSAGE: |
              The components dependencies visualization powered by Arkit
              ![Image]({0})
          with:
            repo-token: ${{ secrets.GITHUB_TOKEN }}
            message: ${{format(env.MESSAGE, env.IMG_URL)}}
