name: Arkit
on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Init
        uses: actions/setup-node@v2
        with:
          node-version: 17
          cache: yarn
      - name: Create the Arkit image
        run: |
          npm install -g yarn
          yarn
          yarn arkit:components
      - name: Upload the image
        uses: devicons/public-upload-to-imgur@v2.2.1
        id: imgur_step
        with:
          path: ./components.png
          client_id: ${{secrets.IMGUR_CLIENT_ID}}
          uses: actions/github-script@v5
          script: |
            github.rest.issues.createComment({
              body: ${{ steps.imgur_step.outputs }}
            })
