name: Gource
on:
  pull_request:
    branches:
      - master

jobs:
  gource:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Init
        uses: actions/setup-node@v2
        with:
          node-version: 17
          cache: yarn
      - name: Install gource
        run: |
          sudo apt-get install gource
          sudo apt-get install ia32-libs-sdl
      - name: Install ffmpeg
        uses: FedericoCarboni/setup-ffmpeg@v1
        id: setup-ffmpeg
      - name: Create Gource video
        run: |
          npm install -g yarn
          yarn
          yarn gource
      - name: Upload video
        uses: devicons/public-upload-to-imgur@v2.2.2
        id: imgur_step
        with:
          path: ./docs-gource.mp4
          client_id: ${{secrets.IMGUR_CLIENT_ID}}
      - name: Make comment
        uses: github-actions-up-and-running/pr-comment@v1.0.1
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
          message: ${{ fromJSON(steps.imgur_step.outputs.markdown_urls)[0] }}
